AWSTemplateFormatVersion: 2010-09-09
Description: Template to create a vpc with a webserver
Resources: 
  webServerVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
  webServerPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: webServerVpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "eu-central-1a"
  myInternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: webServerVpc
      InternetGatewayId:
        Ref: myInternetGateway
